// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8XUPAfKU1qE8v0zynLODrcyCeMOFRsjA',
    appId: '1:331728575499:web:4a0e5ff77f6f1f825c3b0e',
    messagingSenderId: '331728575499',
    projectId: 'ivloovpetsapp',
    authDomain: 'ivloovpetsapp.firebaseapp.com',
    storageBucket: 'ivloovpetsapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjogDzK93SpRLTNTNvg1TBgMyCpGcS7NM',
    appId: '1:331728575499:android:8f33cc0826ea16a75c3b0e',
    messagingSenderId: '331728575499',
    projectId: 'ivloovpetsapp',
    storageBucket: 'ivloovpetsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQB10DHzKjY0LbaSgHNlCbVQkHA_ggGfE',
    appId: '1:331728575499:ios:ecf8f14db0d86edf5c3b0e',
    messagingSenderId: '331728575499',
    projectId: 'ivloovpetsapp',
    storageBucket: 'ivloovpetsapp.appspot.com',
    iosBundleId: 'com.iv.loovpets',
  );
}
